import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useRef } from 'react'
import { useRouter } from 'next/router'
// let socket

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const buttonRef = useRef(null)
  const selectRef = useRef(null)
  const router = useRouter()
  const { push } = useRouter()
  const serviceId = router.query.serviceId || process.env.NEXT_PUBLIC_DEFAULT_SERVICE_ID

  const LANGUAGES = process.env.NEXT_PUBLIC_LANGUAGES.split(',')

  const handleClick = async (e) => {
    if (selectRef.current.value == "") {
      alert("No language is selected")
    } else {
      console.log(`Selected language: ${selectRef.current.value}`)
      await push(`/translate?serviceId=${serviceId}&language=${selectRef.current.value}`)
    }
  }
  return (
    <>
      <Head>
        <title>DeBabel Translation App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
      </Head>
      <div className={styles.home}>
        {/* <h1>Debabel</h1> */}
        <div className={styles.logo}>
          <img src='/logo.png' />
        </div>
        <div className={styles.inputBox}>
          <img src='/NEFC.png' />
          <div className={styles.input}>
            <label>Please select your language</label>
            <select ref={selectRef}>
              {LANGUAGES.map((option, index) => {
                // Alternate between locale and language name
                const locale = LANGUAGES[index * 2]
                const language = LANGUAGES[index * 2 + 1]
                if (locale && language) {

                  return (
                    <option key={locale} value={locale}>{language}</option>
                  )
                }
              })}
            </select>
          </div>
          <div ref={buttonRef} onClick={handleClick} className={styles.translateButton}>
            {/* <a href='/translate'> */}
            TRANSLATE
            {/* </a> */}
          </div>
        </div>
      </div>
    </>
  )
}
