import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {io} from 'socket.io-client'
import { useEffect, useRef } from 'react'
import { useRouter } from 'next/router'
// let socket

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const buttonRef = useRef(null)
  const selectRef = useRef(null)
  const router = useRouter()
  const {push} = useRouter()
  const {serviceId} = router.query


  // useEffect(() => {
  //  socketInitializer()
  // }, [])

  // const socketInitializer = () => {
  //   socket = io('https://live-pegasus-first.ngrok-free.app')
  //   socket.on('connect', () => {
  //     console.log('connected to the socket')
  //   })

  //   socket.on('disconnect', () => {
  //     console.log('disconnected from the socket')
  //   })
  // }

  const handleClick = (e) => {
    if (selectRef.current.value == "") {
      alert("No language is selected")
    } else {
      // alert(`Selected language: ${selectRef.current.value}`)
      console.log(`Selected language: ${selectRef.current.value}`)
      push(`/translate?serviceId=${serviceId}&language=${selectRef.current.value}`)
      // const room = `${serviceId}:${selectRef.current.value}`; 
      // socket.emit('join', room)
    }
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"></link>
      </Head>
      <div className={styles.home}>
        {/* <h1>Debabel</h1> */}
        <div className={styles.logo}>
        <img src='/logo.png' />
        </div>
        <div className={styles.inputBox}>
          <div className={styles.input}>
          <label>Please select your language</label>
          <select ref={selectRef}>
            <option value="en">English</option>
            <option value="ar">Arabic</option>
            <option value="fr">French</option>
            <option value="de">German</option>
            <option value="es">Spanish</option>
            <option value="tr">Turkish</option>
            <option value="uk">Ukranian</option>
          </select>
          </div>
          <div ref={buttonRef} onClick={handleClick} className={styles.translateButton}>
            {/* <a href='/translate'> */}
              TRANSLATE
            {/* </a> */}
          </div>
        </div>
      </div>
    </>
  )
}
